Add no linebreaks in curly braces rule
untile/eslint-config-untile-react pull request #20
Opened 2022-04-18 10:16 UTC by claudiorodr

This PR adds `react/jsx-curly-newline`.

https://user-images.githubusercontent.com/44649923/163794094-8d7f8a7d-4c6f-4d43-9da2-253e2346433f.mov

2022-04-20 17:47 UTC, andrewmoreno requested changes
Just wondering if this will force something like what's seen in the video above. 🤔 

```tsx
<div>{'hey'}</div>
```

2022-04-20 17:47 UTC, andrewmoreno commented on src/index.js
> +    }],
```suggestion
    'react/jsx-curly-newline': ['error', { 
      multiline: 'forbid',
      singleline: 'forbid' 
    }],
```

2022-04-26 10:16 UTC, luisdralves commented on src/index.js
> +    }],
You can pass `'never'` as a string option instead of the explicit object for the same effect

2022-04-26 10:16 UTC, luisdralves commented on test/fixtures/incorrect.js
> +    {
There is a trailing space on this line

2023-03-14 16:27 UTC, closed without merging